name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up ssh
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2.
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            # Debugging: Print current directory
            echo "Current directory: $(pwd)"
            
            # Source nvm if needed
            source ~/.nvm/nvm.sh
            
            # Navigate to the application directory (
            cd /home/ubuntu/F-BEE24001186-km7-azi-banking-system-ch2

            # Ensure the directory is correct
            echo "Navigated to $(pwd)"

            # Pull the latest changes from main branch
            git pull origin main

            # Install dependencies
            npm install

            # Run Prisma generation
            npx prisma generate

            # Restart or start the app with pm2
            pm2 restart my-app || pm2 start app.js --name my-app

            # Save pm2 process list
            pm2 save

            # Print confirmation
            echo "Deployment completed successfully"
          EOF
