name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            # Ensure the project directory exists or clone the repository if not present
            if [ ! -d "F-BEE24001186-km7-azi-banking-system-ch2" ]; then
              git clone https://github.com/your-username/your-repository.git F-BEE24001186-km7-azi-banking-system-ch2
            fi

            # Navigate to the project directory
            cd F-BEE24001186-km7-azi-banking-system-ch2

            # Make sure we're on the correct branch
            git checkout main
            git reset --hard origin/main

            # Install dependencies and generate Prisma client
            npm install
            npx prisma generate

            # Restart the application using PM2
            pm2 restart my-app || pm2 start app.js --name my-app

            # Save PM2 process list and set up startup script
            pm2 save
            pm2 startup systemd --hp /home/ubuntu
            pm2 save
          EOF
